# ===========================================================================
#  PERMISSION & COMMANDS SETTINGS
# ===========================================================================
PERMISSIONS:
  Commands: "clear" # /kick
  Description: "Tömeges üzenet törlése" # command description
  Options:
    Name: "amount" # DON'T CHANGE!!!
    Description: "Add meg a mennyiséget (1-100)" # user description
  CommandsGuildPermissions:
    "1212249645649235998": ["1212412926871207987", "1212451853099474974"] # add multiple permission roles if needed ['1274989008241557580', '127498900824155125']

# ===========================================================================
#  LOG CHANNELS
# ===========================================================================
LOGS_SETTINGS:
  Enabled: true # if true logs will be enabled
  LogChannel:
    "1212249645649235998": "1278453854996009141"
    # Add more guild IDs and log channels as needed

# ===========================================================================
#  LANGUAGE
# ===========================================================================
translate:
  Errors:
    NoPermission: "Nincs jogosultságod a parancs használatához."
    InvalidAmount: "1 és 100 közötti mennyiséget tudsz megadni."
    LogChannelNotFound: "Nem található log csatorna a(z) {guildId} guild ID-hoz"
    ExecutionError: "Hiba történt a parancs végrehajtása közben."
    DeletionError: "Hiba történt az üzenetek törlése közben ebben a csatornában!"
  Success:
    MessageDeleted: "Sikeresen töröltél **[{amount}]** üzenet."
  Log:
    Author: "Tömeges üzenet törlés"
    Command: "Parancs: [Clear]"
    Description: "{amount} üzenetet törlésre került."
    DeletionTime: "Törlés időpontja"
    ChannelUrl: "Csatorna URL"
    User: "Felhasználó"
    Username: "Felhasználónév"
    UserID: "Discord ID:"
    Footer: "{guildName}"

# ===========================================================================
#  EMBED COLORS
# ===========================================================================
EMBED_COLORS:
  Default: "#3498db"
  Error: "#EC7063"
  Success: "#27AE60"
  Log: "#9c640c"
